site_name: ""
site_description: Fast Init for Linux Systems
site_url: http://finit-project.github.io
repo_url: https://github.com/finit-project/finit
repo_name: Finit Project
copyright: Copyright &copy; 2008-2025 Joachim Wiberg
docs_dir: doc/
edit_uri: edit/master/doc/
extra_css:
  - extra.css

exclude_docs: |
  TODO.md
  ChangeLog.md

theme:
  logo: img/logo.png
  name: material
  features:
    - toc.follow
    - toc.integrate
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
#    - navigation.sections
#    - navigation.expand
#    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
#    - content.action.edit
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Getting Started:
    - Introduction: index.md
    - Features: features.md
    - Quick Example: example.md
    - Building: build.md
  - Configuration:
    - Overview: config/index.md
    - Files & Layout: config/files.md
    - Conditions: conditions.md
    - Runlevels: config/runlevels.md
    - One-shot Tasks: config/task-and-run.md
    - Services:
      - Syntax: config/services.md
      - Options: config/service-opts.md
      - Environment: config/service-env.md
      - Synchronization: config/service-sync.md
      - Wrapper Scripts: config/service-wrappers.md
    - Run-parts Scripts: config/runparts.md
    - TTY & Console: config/tty.md
    - Environment Variables: config/env.md
    - Logging: config/logging.md
    - Cgroups: config/cgroups.md
    - Capabilities: config/capabilities.md
    - Templating: config/templating.md
    - SysV Compatibility: config/sysv.md
    - Rescue Mode: config/rescue.md
    - Limitations: config/limitations.md
  - Usage:
    - Commands & Status: initctl.md
    - Rebooting & Halting: commands.md
    - Command Line Options: cmdline.md
    - Managing Services: service.md
    - Signals: signals.md
  - Reference:
    - Runlevels Overview: runlevels.md
    - Runparts & rc.local: runparts.md
    - Plugins: plugins.md
    - Watchdog: watchdog.md
    - keventd: keventd.md
    - Service State Machine: state-machine.md
    - Distributions: distro.md
    - Requirements: requirements.md

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - callouts
  - glightbox

extra:
  homepage: https://finit-project.github.io/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/finit-project/finit
      name: Finit on GitHub
